<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="PaymentServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/PaymentServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/PaymentServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://payment.company.com/">
    <import location="http://localhost:8080/OnlinePaymentCompany/PaymentService?wsdl" namespace="http://payment.company.com/"/>
    <plnk:partnerLinkType name="PaymentLinkType">
        <plnk:role name="PaymentRole" portType="ns:Payment"/>
    </plnk:partnerLinkType>
</definitions>
