<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="StockServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/StockServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/StockServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://shop.provider.com/">
    <import location="http://localhost:8080/ProviderShop/StockService?wsdl" namespace="http://shop.provider.com/"/>
    <plnk:partnerLinkType name="StockLinkType">
        <plnk:role name="StockRole" portType="ns:Stock"/>
    </plnk:partnerLinkType>
</definitions>
