<?xml version="1.0" encoding="UTF-8"?>
<definitions name="procesoPedido" targetNamespace="http://j2ee.netbeans.org/wsdl/PedidosBPEL/Descriptor/procesoPedido"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/PedidosBPEL/Descriptor/procesoPedido" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types/>
    <message name="procesoPedidoOperationRequest">
        <part name="idCliente" type="xsd:string"/>
        <part name="idProducto" type="xsd:string"/>
        <part name="cantidad" type="xsd:int"/>
        <part name="precio" type="xsd:double"/>
    </message>
    <message name="procesoPedidoOperationResponse">
        <part name="part1" type="xsd:string"/>
    </message>
    <portType name="procesoPedidoPortType">
        <operation name="procesoPedidoOperation">
            <input name="input1" message="tns:procesoPedidoOperationRequest"/>
            <output name="output1" message="tns:procesoPedidoOperationResponse"/>
        </operation>
    </portType>
    <binding name="procesoPedidoBinding" type="tns:procesoPedidoPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="procesoPedidoOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/PedidosBPEL/Descriptor/procesoPedido"/>
            </input>
            <output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/PedidosBPEL/Descriptor/procesoPedido"/>
            </output>
        </operation>
    </binding>
    <service name="procesoPedidoService">
        <port name="procesoPedidoPort" binding="tns:procesoPedidoBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/procesoPedidoService/procesoPedidoPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="procesoPedido">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="procesoPedidoPortTypeRole" portType="tns:procesoPedidoPortType"/>
    </plnk:partnerLinkType>
</definitions>
